# Generated by Django 3.2.22 on 2024-03-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20240314_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromtable',
            name='account_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
