# Generated by Django 3.2.22 on 2024-02-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('decsription', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images')),
            ],
        ),
    ]
