# Generated by Django 3.2.22 on 2024-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=70, unique=True)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Branches_Home',
        ),
    ]
